package ru.xtool.tests;// Generated by Selenium IDE
import com.codeborne.selenide.SelenideDriver;

import static com.codeborne.selenide.Selenide.sleep;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Order;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ArgumentsSource;
import ru.xtool.pages.*;

public class AnalyzeTest {
  //private static SelenideDriver driver = new SelenideDriver(new SelenideConfig().browser("chrome").browserSize("1280x1024").timeout(20000));
  private static AnalyzePage analyzePage;
  private static MainPage mainPage;
  private static AccountPage accountPage;
  static void openAnalyzePage(SelenideDriver driver) {
    analyzePage = new AnalyzePage(driver);
    driver.open(AnalyzePage.url);
  }
  static void login(SelenideDriver driver) {
    mainPage = new MainPage(driver);
    accountPage = new AccountPage(driver);
    driver.open(MainPage.url);
    mainPage.sendLoginData();
    sleep(1000);
  }
  @ParameterizedTest(name = "[{index}] site: {0}")
  @ArgumentsSource(WebDriverArgumentProvider.class)
  @Order(1)
  public void testAnalyzeCiteUnauthorized(SelenideDriver driver) {
    String url = "github.com";
    openAnalyzePage(driver);
    analyzePage.analyzeCite(url);
    sleep(1000);
    assertEquals(analyzePage.getAnalyzedUrl(), url);
  }
  @ParameterizedTest(name = "[{index}] site: {0}")
  @ArgumentsSource(WebDriverArgumentProvider.class)
  @Order(2)
  public void testAnalyzeCiteAuthorized(SelenideDriver driver) {
    String url = "github.com";
    login(driver);
    openAnalyzePage(driver);
    analyzePage.analyzeCite(url);
    sleep(3000);
    assertEquals(analyzePage.getAnalyzedUrl(), url);
    driver.open(ChecksPage.url);
    assertEquals(accountPage.getCheckedUrl(), url);
  }
}
