package ru.xtool.tests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void region() {
    driver.get("https://xtool.ru/");
    driver.manage().window().setSize(new Dimension(1370, 786));
    driver.findElement(By.linkText("Регион сайта")).click();
    driver.findElement(By.cssSelector(".list-group-item:nth-child(10)")).click();
    driver.findElement(By.id("url")).click();
    driver.findElement(By.id("url")).sendKeys("https://github.com/");
    driver.findElement(By.id("check-submit")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".recaptcha-checkbox-border")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.id("check-submit")).click();
    js.executeScript("window.scrollTo(0,15)");
    driver.findElement(By.cssSelector(".center:nth-child(3)")).click();
    driver.findElement(By.id("url")).sendKeys("vk.com");
    driver.findElement(By.cssSelector(".audit")).click();
    js.executeScript("window.scrollTo(0,245)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".trust")).click();
    vars.put("win1057", waitForWindow(2000));
    assertEquals(driver.switchTo().alert().getText(), "Введите YES для подтверждения перехода на сайт https://vk.com");
    {
      Alert alert = driver.switchTo().alert();
      alert.sendKeys("YES");
      alert.accept();
    }
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win1057").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
  }
}
